name: Stream Service CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read
  packages: read

env:
  GCP_PROJECT: boredsoftwaredev
  GCP_REGION: us-central1
  AR_REPO: backend
  SERVICE_NAME: stream-service
  RUNTIME_SA: cloud-run-runtime@boredsoftwaredev.iam.gserviceaccount.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build & test
        run: ./gradlew clean check
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/849094850972/locations/global/workloadIdentityPools/github/providers/github-provider
          service_account: github-deployer@boredsoftwaredev.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_BUILDKIT: "1"
        run: |
          docker build \
            --secret id=gh_actor,env=GITHUB_ACTOR \
            --secret id=gh_token,env=GITHUB_TOKEN \
            -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.AR_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.AR_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.AR_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.GCP_REGION }} \
            --platform managed \
            --no-allow-unauthenticated \
            --service-account=${{ env.RUNTIME_SA }} \
            --min-instances=0 \
            --max-instances=2 \
            --memory=1Gi \
            --cpu=1 \
            --concurrency=80 \
            --timeout=60 \
            --set-secrets=DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,SUPABASE_URL=SUPABASE_URL:latest \
            --set-env-vars=LOG_FORMAT=ecs,SUPABASE_DB_HOST=aws-1-ap-southeast-2.pooler.supabase.com
